//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Units.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GRPMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_GRPMST()
        {
            this.tbl_ITEMAS = new HashSet<tbl_ITEMAS>();
        }
    
        public int Grpmst_id { get; set; }
        public string Group_code { get; set; }
        public string Group_name { get; set; }
        public string Und_group { get; set; }
        public string Group_desc { get; set; }
        public Nullable<int> Untmst_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ITEMAS> tbl_ITEMAS { get; set; }
        public virtual tbl_UNTMST tbl_UNTMST { get; set; }
    }
}
